export const images = [
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/0IVv_cOZeY4Uy09sPRtMu.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/6X7tZ0W-thI6NhziV5-6n.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/6X7tZ0W-thI6NhziV5-6n.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/6X7tZ0W-thI6NhziV5-6n.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/6X7tZ0W-thI6NhziV5-6n.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/6X7tZ0W-thI6NhziV5-6n.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/DsgJ5MQnO7-vGz9PUVqN5.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/DsgJ5MQnO7-vGz9PUVqN5.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/DsgJ5MQnO7-vGz9PUVqN5.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/H5vgt3L9rK4As07n-7LUX.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/H5vgt3L9rK4As07n-7LUX.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/L0tmida2pQp_eaaSKikkp.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/OJIcSrCNaiB470n4HwRt7.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/OV8Zta0wIejA35ZxSNDP3.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/OV8Zta0wIejA35ZxSNDP3.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/TQ8sNoTwLPzO4_5t2Y1xg.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/V9TONWZ4TGHsdBHu0b1AX.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/W4mjVSWRZ5u_Q8oed3MC0.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/XKIR83779TBx5fb-yD35D.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/XKIR83779TBx5fb-yD35D.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/YqX-VBvZIRJDuFFN4co93.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/YqX-VBvZIRJDuFFN4co93.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/YqX-VBvZIRJDuFFN4co93.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/aszi5Fn0Y5AZpScFCaYip.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/cBOHSXqcxA3wgdo31PohC.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/cBOHSXqcxA3wgdo31PohC.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/iQg-EgOeV8xDI3uxdx2tD.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/kw9b1z5--VQrnzTvohAAI.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/mp4G5mEu1A9ApGyk7J8UH.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/mp4G5mEu1A9ApGyk7J8UH.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/mp4G5mEu1A9ApGyk7J8UH.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/mp4G5mEu1A9ApGyk7J8UH.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/mp4G5mEu1A9ApGyk7J8UH.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/rpnVB5uzzr-uagvwwNxGL.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/rpnVB5uzzr-uagvwwNxGL.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/rpnVB5uzzr-uagvwwNxGL.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/rpnVB5uzzr-uagvwwNxGL.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/wpjNXq8wStewL1n4yaJeB.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/wpjNXq8wStewL1n4yaJeB.png',
  'https://yxoqmnwlixhxdxtgjthx.supabase.co/storage/v1/object/public/rooms/zdePKdECjJh2NwPt29_Et.png',
]

const getRandomImage = () => images[Math.floor(Math.random() * images.length)]

export default getRandomImage
